# ============================================
# TienditaCampus - Prometheus Config
# ============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:3001"]
    metrics_path: "/api/metrics"

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/health"

  - job_name: "postgres"
    static_configs:
      - targets: ["database:5432"]
